# Generated by Django 4.2.6 on 2023-10-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffee_Shop_Management', '0002_paycheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycheck',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
